# Generated by Django 5.0.4 on 2024-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seat_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default='../', max_length=1000),
        ),
    ]
